import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data } = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <h1>
            ROCM Esports
          </h1>
          <div>
            {data ? <p>{data.greeting}</p> : <p>Loading...</p>}
          </div>
        </div>
        <AuthComponent />
      </div>
    </>
  );
};

const AuthComponent = () => {
  const { data: secretMessage } = trpc.useQuery(['auth.getSecretMessage'])
  const { data: sessionData } = useSession()
  
  return (
    <div>
      {sessionData && <p>{sessionData.user?.name}</p>}
      {secretMessage && <p>{secretMessage}</p>}
      <button onClick={sessionData ? () => signOut() : () => signIn()}>
          {sessionData ? "Sign Out" : "Sign In"}
      </button>
    </div>
  )
}

export default Home;
