import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const { data: session } = useSession();
  
  if (!session) {
    return (
      <div>
        <p>you are not logged in</p>
        <button onClick={() => signIn()}>Sign In</button>
      </div>
    )
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <h1>
            ROCM Esports
          </h1>
          <p>welcome { session.user?.name}</p>
          <button onClick={() => signOut()}>Sign Out</button>
        </div>
      </div>
    </>
  );
};



export default Home;
